In [62]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='openpyxl')

In [88]:
tb1 = pd.read_excel("item_base.xlsx", sheet_name=2, header=6, usecols=[1,3])
tb1

           id        strItemName
0      102101   Item_name_102101
1      102102   Item_name_102102
2      102103   Item_name_102103
3      102104   Item_name_102104
4      103101   Item_name_103101
...       ...                ...
1892  8100021  Item_name_8100021
1893  8100022  Item_name_8100022
1894  8100023  Item_name_8100023
1895  8100024  Item_name_8100024
1896  8100025  Item_name_8100025

[1897 rows x 2 columns]

In [64]:
tb2 = pd.read_excel('String.xlsx', header=1, usecols=[1,2])
tb2.rename(columns = {'stringkey':'strItemName'},inplace=True)
tb2

                   strItemName                                       KOR
0             Item_name_102101                                   약탈자의 강검
1             Item_name_102102                                   잊혀진 수집검
2             Item_name_102103                                   가벼운 한손검
3             Item_name_102104                                    복수의 장검
4             Item_name_103101                                   추적자의 강검
...                        ...                                       ...
2774  Item_description_8100021                                탐험의 증표입니다.
2775  Item_description_8100022     아르델 상점에서 사용이 가능합니다.\n장신구를 뽑을 때 사용됩니다.
2776  Item_description_8100023  아르델 상점에서 사용이 가능합니다.\n값진 장신구를 뽑을 때 사용됩니다.
2777  Item_description_8100024                         거래소에서 사용되는 재화입니다.
2778  Item_description_8100025                    상점에서 사용할 수 있는 마일리지입니다.

[2779 rows x 2 columns]

In [79]:
tb3 = tb1.merge(tb2, on=['strItemName'], how='left')
tb3 = tb3[['KOR']]
tb3

            KOR
0       약탈자의 강검
1       잊혀진 수집검
2       가벼운 한손검
3        복수의 장검
4       추적자의 강검
...         ...
1892     탐험의 징표
1893  실버 아르델 주화
1894  골드 아르델 주화
1895     블루 루메나
1896    상점 마일리지

[1897 rows x 1 columns]

In [92]:
with pd.ExcelWriter("Item_Base.xlsx", mode='a', engine="openpyxl", if_sheet_exists="overlay") as writer:
    tb3.to_excel(writer, sheet_name=2, columns=2)

BadZipFile: File is not a zip file